ALTER TABLE PACIENTE
ADD CONSTRAINT PACIENTE_MEDICO_FK FOREIGN KEY(Medico)
REFERENCES PERSONAL(Cedula);

ALTER TABLE CAMA
ADD CONSTRAINT CAMA_SALON_FK FOREIGN KEY(Salon)
REFERENCES SALON(SalonID);

ALTER TABLE CAMA
ADD CONSTRAINT CAMA_EQUIPO_FK FOREIGN KEY(EquipoMedico)
REFERENCES Equipo_Medico(EquipoID);

ALTER TABLE RESERVACION
ADD CONSTRAINT RESERVACION_PACIENTE_FK FOREIGN KEY(Paciente)
REFERENCES Paciente(Cedula);

ALTER TABLE RESERVACION
ADD CONSTRAINT RESERVACION_PROCEDIMIENTO_FK FOREIGN KEY(Procedimiento)
REFERENCES PROCEDIMIENTO(ProcedimientoID);

ALTER TABLE HISTORIAL_CLINICO
ADD CONSTRAINT HISTORIAL_PACIENTE_FK FOREIGN KEY(Paciente)
REFERENCES Paciente(Cedula);

ALTER TABLE HISTORIAL_CLINICO
ADD CONSTRAINT HISTORIAL_PROCEDIMIENTO_FK FOREIGN KEY(Procedimiento)
REFERENCES PROCEDIMIENTO(ProcedimientoID);